"""empty message

Revision ID: 604da5c02d8d
Revises: 
Create Date: 2020-02-07 00:37:48.743984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604da5c02d8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_begin', sa.DateTime(), nullable=False),
    sa.Column('date_until', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
